Add pixel and intensity functions.
efrits-fr/led_matrix_max7219_arduino_library pull request #13
Opened 2021-12-20 23:33 UTC by Damdoshi

2021-12-21 08:33 UTC, monpierrelisa requested changes

2021-12-21 08:33 UTC, monpierrelisa commented on sources/led_matrix_max7219/ledMatrixMax7219.cpp
> +void LedMatrixMax7219::setIntensity(byte a, byte b, byte c, byte d)
Please add a real name for these variables

2021-12-21 08:33 UTC, monpierrelisa commented on sources/led_matrix_max7219/ledMatrixMax7219.cpp
> +  delay(500);
delay 50 is sufficient normally no ?

2021-12-21 08:33 UTC, monpierrelisa commented on sources/led_matrix_max7219/ledMatrixMax7219.cpp
> +  delay(500);
delay 50 is sufficient normally no ?

2021-12-21 08:33 UTC, monpierrelisa commented on sources/led_matrix_max7219/ledMatrixMax7219.cpp
> +  if (color)
add {}

2021-12-21 08:33 UTC, monpierrelisa commented on sources/led_matrix_max7219/ledMatrixMax7219.cpp
> +{
move these getter in .h to become inlined function

2021-12-21 10:04 UTC, Damdoshi commented on sources/led_matrix_max7219/ledMatrixMax7219.cpp
> +  delay(500);
The init sequence that allow the card to be well reseted use 500ms as delay in those places.

2021-12-21 10:04 UTC, Damdoshi commented on sources/led_matrix_max7219/ledMatrixMax7219.cpp
> +  delay(500);
The init sequence that allow the card to be well reseted use 500ms as delay in those places.

2021-12-21 10:05 UTC, Damdoshi commented on sources/led_matrix_max7219/ledMatrixMax7219.cpp
> +void LedMatrixMax7219::setIntensity(byte a, byte b, byte c, byte d)
intensity_level_for_matrix_a ?

2021-12-21 22:24 UTC, Damdoshi commented
Changes are done.

2021-12-22 10:32 UTC, monpierrelisa approved these changes

2021-12-22 10:42 UTC, merged