Issue 18
efrits-fr/led_matrix_max7219_arduino_library pull request #19
Opened 2021-12-28 12:00 UTC by Damdoshi

2021-12-30 20:22 UTC, monpierrelisa requested changes

2021-12-30 20:22 UTC, monpierrelisa commented on sources/examples/8x32_led_matrix_max7219/8x32_led_matrix_max7219.ino
> +  // Allow the matrix to work correctly
// Initialization of the matrix, allow it to work correctly

2021-12-30 20:22 UTC, monpierrelisa commented on sources/examples/8x32_led_matrix_max7219/8x32_led_matrix_max7219.ino
> +// This function is only called at startup once
This function is only called once at startup to set up the demo

2021-12-30 20:22 UTC, monpierrelisa commented on sources/examples/8x32_led_matrix_max7219/8x32_led_matrix_max7219.ino
> +  // Set the horizontal ball position somewhere between 0 and the width of the screen randombly
ramdomly

2021-12-30 20:22 UTC, monpierrelisa commented on sources/examples/8x32_led_matrix_max7219/8x32_led_matrix_max7219.ino
> +  // Set the vertical ball position somewhere between 0 and the height of the screen randombly
ramdomly

2021-12-30 20:22 UTC, monpierrelisa commented on sources/examples/8x32_led_matrix_max7219/8x32_led_matrix_max7219.ino
> +  // Set different brightness levels of matrix, so a little variety appeirs when balls move from
appears

2021-12-30 20:22 UTC, monpierrelisa commented on sources/examples/8x32_led_matrix_max7219/8x32_led_matrix_max7219.ino
> +// This function is called repeatidly
repeatedly

2021-12-30 20:59 UTC, Damdoshi commented on sources/examples/8x32_led_matrix_max7219/8x32_led_matrix_max7219.ino
> +  // Set the horizontal ball position somewhere between 0 and the width of the screen randombly
randomly

2022-01-01 20:06 UTC, monpierrelisa approved these changes

2022-01-01 20:50 UTC, merged